version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack-name = "staging-todo-list-aws"
s3-bucket = "aws-sam-cli-managed-default-samclisourcebucket-tpbrtihbizum"
s3-prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter-overrides = "Stage=\"staging\""
image-repositories = []
